## YAML Template.
---
Spring:
  application:
    name: TEST-BACK
  devtools:
    restart:
      enabled: true
    livereload:
      enabled: true
  datasource:

    url: jdbc:sqlserver://localhost;databaseName=
    username:
    password:

  driverClassName: com.microsoft.sqlserver.jdbc.SQLServerDriver
  jpa:
    show-sql: true
    hibernate:
      dialect: org.hibernate.dialect.SQLServer2012Dialect
      ddl-auto: create
server:
  port: 8080